const db: { 
    episode: number;
    season: number;
    fileName?: string;
}[] = [
    {episode: 1, season: 1, fileName: 'animevost_1-seriya-Ataka-titanov-480p.mp4'},
    {episode: 2, season: 1, fileName: 'animevost_2-seriya-Ataka-titanov-480p.mp4'},
    {episode: 3, season: 1, fileName: 'animevost_3-seriya-Ataka-titanov-480p.mp4'},
    {episode: 4, season: 1},
    {episode: 5, season: 1},
    {episode: 6, season: 1},
    {episode: 7, season: 1},
    {episode: 8, season: 1},
    {episode: 9, season: 1},
    {episode: 10, season: 1},
    {episode: 11, season: 1},
    {episode: 12, season: 1},
    {episode: 13, season: 1},
    {episode: 14, season: 1},
    {episode: 15, season: 1},
    {episode: 16, season: 1},
    {episode: 17, season: 1},
    {episode: 18, season: 1},
    {episode: 19, season: 1},
    {episode: 20, season: 1},
    {episode: 21, season: 1},
    {episode: 22, season: 1},
    {episode: 23, season: 1},
    {episode: 24, season: 1},
    {episode: 25, season: 1},
    {episode: 1, season: 2},
    {episode: 2, season: 2},
    {episode: 3, season: 2},
    {episode: 4, season: 2},
    {episode: 5, season: 2},
    {episode: 6, season: 2},
    {episode: 7, season: 2},
    {episode: 8, season: 2},
    {episode: 9, season: 2},
    {episode: 10, season: 2},
    {episode: 11, season: 2},
    {episode: 12, season: 2},
    {episode: 1, season: 3},
    {episode: 2, season: 3},
    {episode: 3, season: 3},
    {episode: 4, season: 3},
    {episode: 5, season: 3},
    {episode: 6, season: 3},
    {episode: 7, season: 3},
    {episode: 8, season: 3},
    {episode: 9, season: 3},
    {episode: 10, season: 3},
    {episode: 11, season: 3},
    {episode: 12, season: 3},
    {episode: 13, season: 3},
    {episode: 14, season: 3},
    {episode: 15, season: 3},
    {episode: 16, season: 3},
    {episode: 17, season: 3},
    {episode: 18, season: 3},
    {episode: 19, season: 3},
    {episode: 20, season: 3},
    {episode: 21, season: 3},
    {episode: 22, season: 3},
    {episode: 1, season: 4},
    {episode: 2, season: 4},
    {episode: 3, season: 4},
    {episode: 4, season: 4},
    {episode: 5, season: 4},
    {episode: 6, season: 4},
    {episode: 7, season: 4},
    {episode: 8, season: 4},
    {episode: 9, season: 4},
    {episode: 10, season: 4},
    {episode: 11, season: 4},
    {episode: 12, season: 4},
    {episode: 13, season: 4},
    {episode: 14, season: 4},
    {episode: 15, season: 4},
    {episode: 16, season: 4},
    {episode: 17, season: 4},
    {episode: 18, season: 4},
    {episode: 19, season: 4},
    {episode: 20, season: 4},
    {episode: 21, season: 4},
    {episode: 22, season: 4},
    {episode: 23, season: 4},
    {episode: 24, season: 4},
    {episode: 25, season: 4},
    {episode: 26, season: 4},
    {episode: 27, season: 4},
    {episode: 28, season: 4},
    {episode: 29, season: 4},
];

export default db;